### ISSUE TITLE
Exception in the new state saving code

### ISSUE THREAD

**Issue by jhford** [taskcluster/aws-provisioner#136]
```
2017-03-07T12:40:29.734821+00:00 app[provisioner.1]: 12:40:29.733Z ERROR aws-provisioner-staging: error writing state using azure-blob-storage (workerType=cli)
2017-03-07T12:40:29.734831+00:00 app[provisioner.1]:     TypeError: Cannot read property 'createDataBlockBlob' of undefined
2017-03-07T12:40:29.734832+00:00 app[provisioner.1]:         at Provisioner._callee2$ (/app/src/provision.js:218:15)
2017-03-07T12:40:29.734833+00:00 app[provisioner.1]:         at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)
2017-03-07T12:40:29.734834+00:00 app[provisioner.1]:         at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:299:22)
2017-03-07T12:40:29.734837+00:00 app[provisioner.1]:         at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:116:21)
2017-03-07T12:40:29.734838+00:00 app[provisioner.1]:         at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
2017-03-07T12:40:29.734839+00:00 app[provisioner.1]:         at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
2017-03-07T12:40:29.734840+00:00 app[provisioner.1]:         at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by jhford** [comment]
@elenasolomon in case you have a chance to look at this

**Comment by jhford** [comment]
hmm, i think I found the problem, patch incoming

**Comment by jhford** [comment]
Hmmmmm.
```
TypeError: Cannot create property 'container' on string 'tutorial'
    at DataContainer._callee7$ (/home/jhford/taskcluster/aws-provisioner/node_modules/azure-blob-storage/src/datacontainer.js:298:5)
    at tryCatch (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/home/jhford/taskcluster/aws-provisioner/node_modules/core-js/library/modules/_export.js:35:28)
    at DataContainer.<anonymous> (/home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at DataContainer.createDataBlockBlob (/home/jhford/taskcluster/aws-provisioner/node_modules/azure-blob-storage/lib/datacontainer.js:587:22)
    at Provisioner._callee2$ (/home/jhford/taskcluster/aws-provisioner/src/provision.js:222:38)
    at tryCatch (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
undefined
```
